apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-upgrade
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-cguttman-tenant/demo-upgrade/demo-upgrade@sha256:da8325e23ef20e4b3de8314330df0a3194e63ea35781ded528217a46c66a2638
        name: my-java-springboot
        resources: {}
status: {}
