apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-upgrade
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-cguttman-tenant/demo-upgrade/demo-upgrade@sha256:f1407d95c0658dd86fa2d1731c277fe58efed13e6db71bcbf9bd7b586f9e1766
        name: my-java-springboot
        resources: {}
status: {}
